title: Vergelijkingsoperatoren
hero_image: images/banner.png
description: Vergelijkingsoperatoren in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Vergelijkingsoperatoren gebruiken
